/** @type {Record<string, import('../utils/index.js').Props>} */
export const colorProp: Record<string, import("../utils/index.js").Props>;
/** @type {Record<string, import('../utils/index.js').Props>} */
export const sizeNumberProp: Record<string, import("../utils/index.js").Props>;
/** @type {Record<string, import('../utils/index.js').Props>} */
export const gapProp: Record<string, import("../utils/index.js").Props>;
/** @type {Record<string, import('../utils/index.js').Props>} */
export const sizeProp: Record<string, import("../utils/index.js").Props>;
/** @type {Record<string, import('../utils/index.js').Props>} */
export const shapeProp: Record<string, import("../utils/index.js").Props>;
/** @type {Record<string, import('../utils/index.js').Props>} */
export const appearanceProp: Record<string, import("../utils/index.js").Props>;
/** @type {Record<string, import('../utils/index.js').Props>} */
export const modeProp: Record<string, import("../utils/index.js").Props>;
/** @type {Record<string, import('../utils/index.js').Props>} */
export const loadingProp: Record<string, import("../utils/index.js").Props>;
