# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package (NPM)

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm publish -w components
      - run: npm i
      - run: npm run build -w packages/react
        continue-on-error: true
      - run: npm publish -w packages/react
        continue-on-error: true
      - run: npm run build -w packages/preact
        continue-on-error: true
      - run: npm publish -w packages/preact
        continue-on-error: true
      - run: npm run build -w packages/svelte
        continue-on-error: true
      - run: npm publish -w packages/svelte
        continue-on-error: true
      - run: npm run build -w packages/vue
        continue-on-error: true
      - run: npm publish -w packages/vue
        continue-on-error: true
