name: Node.js Package (GitHub)

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm i
      - run: npm run decl -w components
      - run: npm publish -w components
        continue-on-error: true
      - run: npm run build -w packages/react
        continue-on-error: true
      - run: npm publish -w packages/react
        continue-on-error: true
      - run: npm run build -w packages/preact
        continue-on-error: true
      - run: npm publish -w packages/preact
        continue-on-error: true
      - run: npm run build -w packages/svelte
        continue-on-error: true
      - run: npm publish -w packages/svelte
        continue-on-error: true
      - run: npm run build -w packages/vue
        continue-on-error: true
      - run: npm publish -w packages/vue
        continue-on-error: true
