name: Node.js Package
on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        registry:
          - url: https://registry.npmjs.org/
            token: 'npm'
          - url: https://npm.pkg.github.com/
            token: 'github'
        package:
          - name: 'components'
            build: false
          - name: 'packages/react'
            build: true
          - name: 'packages/preact'
            build: true
          - name: 'packages/solid'
            build: true
          - name: 'packages/svelte'
            build: true
          - name: 'packages/vue'
            build: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ matrix.registry.token == 'npm' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN}}
        with:
          node-version: 20
          registry-url: ${{ matrix.registry.url }}

      - run: npm i
      - run: npm run decl -w components
        continue-on-error: true

      - name: Build ${{ matrix.package.name }}
        if: ${{ matrix.package.build }}
        run: npm run build -w ${{ matrix.package.name }}

      - name: Publish ${{ matrix.package.name }}
        run: npm publish -w ${{ matrix.package.name }}
